version: 2

models:
  - name: stg_telegram_messages
    description: "Staging model for cleaning Telegram messages."
    columns:
      - name: message_id
        description: "Unique ID of the message"
        tests:
          - not_null
          - unique
      - name: channel_name
        description: "Telegram channel name"
        tests:
          - not_null
models:
  - name: stg_image_detections
    columns:
      - name: detection_id
        tests: [not_null, unique]
      - name: message_id
        tests:
          - not_null
          - relationships:
              to: ref('stg_telegram_messages')
              field: message_id
      - name: detected_object_class
        tests: [not_null]
      - name: confidence_score
        tests: [not_null]