version: 2

models:
  - name: stg_telegram_messages
    description: "Staging model for cleaning Telegram messages."
    columns:
      - name: message_id
        description: "Unique ID of the message"
        tests:
          - not_null
          - unique
      - name: channel_name
        description: "Telegram channel name"
        tests:
          - not_null
