services:
  app:
    build: .
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
    command: ["sh", "wait-for-db.sh", "db", "5432", "python", "app/main.py"]

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"  # Optional: expose for local access
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
