version: 2

models:
  - name: fct_image_detections
    columns:
      - name: detection_id
        tests: [not_null, unique]
      - name: message_id
        tests:
          - not_null
          - relationships:
              to: ref('fct_messages')
              field: message_id
      - name: detected_object_class
        tests: [not_null]
      - name: confidence_score
        tests: [not_null]
